Feature/js 19 259 table/pagination
saritasa-nest/camp-js-2022-karina-popova pull request #2
Opened 2022-02-07 07:47 UTC by karbik-creator

2022-02-07 07:53 UTC, golovachev-yaroslav requested changes

2022-02-07 07:53 UTC, golovachev-yaroslav commented on vanilla/src/index.html
> +        <li class="waves-effect prevBtn disabled">
Is it possible to use kebab_case or camelCase only?

2022-02-07 07:53 UTC, golovachev-yaroslav commented on vanilla/src/pagination/pagination.ts
> +export function disabledВutton(): void {
`disabledВutton` looks like a function that returns a button state(true or false). Need to call more informative and function description as well.

2022-02-07 09:01 UTC, kristinaSvobodinaSaritasa commented on vanilla/src/enum/enum.ts
> +export enum PageArrow {
For my opinion, it is not good name. Please try to rename for better understanding.

2022-02-07 10:16 UTC, panov-aleksey-saritasa commented on vanilla/src/pagination/pagination.ts
> +export function disabledВutton(): void {
I agree, you can read our [article in wiki](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#naming-functions) related to function namings

2022-02-07 10:46 UTC, timofei-maximov-saritasa requested changes

2022-02-07 10:46 UTC, timofei-maximov-saritasa commented on vanilla/src/films/film.ts
> +  director: string;
Please, add `readonly`.

2022-02-07 10:46 UTC, timofei-maximov-saritasa commented on vanilla/src/pagination/pagination.ts
> +const prevBtn = document.querySelector<Element>('.prevBtn');
Please, [avoid using contractions](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#avoid-contractions)

2022-02-07 10:46 UTC, timofei-maximov-saritasa commented on vanilla/src/pagination/pagination.ts
> +export async function pagination(pageArrow: PageArrow): Promise<void> {
Same with [namings](https://github.com/saritasa-nest/camp-js-2022-karina-popova/pull/2/files#r800387189)
Also, documentation doesn't tell anything informative here, please, improve it.

2022-02-07 10:46 UTC, timofei-maximov-saritasa commented on vanilla/src/ts/getDocsFilms.ts
> + * Film.
It's very hard to read. I can't get what is going on according to your docs. 
You have good example [here](vanilla/src/ts/getQueryLimit.ts)

2022-02-07 10:51 UTC, panov-aleksey-saritasa requested changes

2022-02-07 10:51 UTC, panov-aleksey-saritasa commented on vanilla/src/films/getPatternFilms.ts
> + * @returns Films list.
But from returning type of your function it seems that it does not return a list, but a string, could you improve docs?

2022-02-07 10:51 UTC, panov-aleksey-saritasa commented on vanilla/src/films/renderFilms.ts
> +export const pageLimit = 3;
You should [name](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#naming-entities) global constants like this: `PAGE_LIMIT`

2022-02-07 10:51 UTC, panov-aleksey-saritasa commented on vanilla/src/pagination/pagination.ts
> +  });
Please, always stick to one approach when working with Promises throughout your application. Either `async/await` or `then`

2022-02-07 10:51 UTC, panov-aleksey-saritasa commented on vanilla/src/index.html
> +        <li class="waves-effect prevBtn disabled">
I think usage of `ul` + `li` is semantically incorrect here since elements in this list are not homogeneous

2022-02-07 10:51 UTC, panov-aleksey-saritasa commented on vanilla/src/index.html
> +        <li class="waves-effect prevBtn disabled">
Shouldn't it be `<button>` instead? You imply that even in class name

2022-02-07 10:51 UTC, panov-aleksey-saritasa commented on vanilla/src/index.html
> +        <li class="active numberPage"><a>1</a></li>
Could you explain the reason, please, why you wrap page number in anchor tag? It seems unnecessary.

2022-02-08 03:19 UTC, golovachev-yaroslav approved these changes

2022-02-08 04:57 UTC, elena-dragunova approved these changes

2022-02-08 08:26 UTC, timofei-maximov-saritasa approved these changes

2022-02-08 08:26 UTC, timofei-maximov-saritasa commented on vanilla/src/pagination/pagination.ts
> +export async function pagination(changePage: ChangePage): Promise<void> {
`pagination`  is not a good name for a function. As for me, it seems like it is some kind of object with pagination-related properties. I would recommend you to rename it with something like this `managePagination` or `handlePagination`.
You can read more about naming functions [here](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#naming-functions)

2022-02-08 08:55 UTC, panov-aleksey-saritasa approved these changes

2022-02-08 08:55 UTC, panov-aleksey-saritasa commented on vanilla/src/enum/enum.ts
> +}
1) We are not writing `@param` tags for enum, instead we are writing comments for each key of enum. Like this:
```ts
/** Change page. */
export enum ChangePage {

  /** Next. */
  Next = 'next',
  
  /** ... */
  Prev = 'prev',
}
```
2) Please try to use names for entities that have some meaning and have relation to real world. 'ChangePage' sounds strange, don't you agree? I think in your case you could name it like `PaginationDirection`

2022-02-09 01:52 UTC, pavel-romanov8 requested changes

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/films/film.ts
> +  /** The date or string format of the time that this resource was created.*/
What does `string` have to do with `Date`? Please improve your documentation

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/films/film.ts
> +  /** The date format of the time that this resource was edited.*/
We are not describing fields from a data type perspective, because it is already obvious that you have a date format. Please, improve documentation

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/films/film.ts
> +  /** Сollection document id .*/
It is not clear what collection are you talking about here. If it is some firestore collection then I suggest you omit this description, because we shouldn't mix third-party service like firestore in our domain model.

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/enum/enum.ts
> +}
We can omit documentation for each enum field if their meaning is obvious. F.e:
```
enum DateInterval {
  Year = 'year'
  Month = 'month'
  ...e.t.c.
}
```

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/enum/enum.ts
> +export enum ChangePage {
Btw, we don't use verbs to describe nouns. I think `PaginationDirection` will be just fine.

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/films/getFilms.ts
> + * @returns Promise<Film[]>.
There is no need to add `returns` since we already see return type in function signature

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/films/getFilms.ts
> + * Get array films.
Typo, `Get array of films.`

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/films/getFilms.ts
> + * @param collectionFilmsReference A CollectionReference object can be used for adding documents,
I guess we can shorten the name to `collectionReference`. It is already obvious that reference belongs to films since it is used in `getFilms` function

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/films/getFilms.ts
> +        title: doc.data().fields.title,
You can improve it even more:
```
const { fields } = doc.data();
```

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/films/getFilms.ts
> +  const films = querySnapshot.docs.map(doc => {
It seems like a redundant variable. You can return it right away:
```
return querySnapshot.docs.map(.....);
```

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/ts/getDocsFilms.ts
> +  const querySnapshot = await getDocs(collectionFilmsReference);
Redundant variable

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/films/getPatternFilms.ts
> +export function getPatternFilms(catalogFilms: Film[]): string {
You are not mutating `catalogFilms` anywhere, let's make it `readonly Film[]` just to make the contract for the function clients more verbose.

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/pagination/pagination.ts
> +const nextButton = document.querySelector<Element>('.next-button');
`Element` is a too common type for all HTML objects. Here you can use `HTMLButtonElement` to be more descriptive

2022-02-09 01:52 UTC, pavel-romanov8 commented on vanilla/src/ts/getDocsFilms.ts
> +export async function getDocsFilms(
In the description, i see that it can fetch documents from **any** collection, but the name says that it can only be a film. Please, improve function naming.

Also, i suggest you add a generic for the function like:
```
getDocuments<T>(reference: CollectionReference): T {}
```
That way you can reduce the usage of `DocumentData` which is a too generic type.

2022-02-09 09:22 UTC, dbitkovski approved these changes

2022-02-09 09:22 UTC, dbitkovski commented on vanilla/src/films/getPatternFilms.ts
> + * @returns List of films in string format.
If you want to add `@returns` tag let's come up with a better description. As I understand the function returns not a list of stringified films but the HTML code that might be used to create dom elements later

2022-02-09 09:43 UTC, merged