Feature/JC19-276 search
saritasa-nest/camp-js-2022-karina-popova pull request #3
Opened 2022-02-09 11:29 UTC by artem-sotnichenko-saritasa

2022-02-09 11:33 UTC, golovachev-yaroslav approved these changes

2022-02-09 12:05 UTC, timofei-maximov-saritasa commented on vanilla/src/index.html
> +        <input placeholder="Search" type="text" class="search__input">
It's better to use type `search` here to improve semantics

2022-02-09 12:05 UTC, timofei-maximov-saritasa commented on vanilla/src/ts/getQuerySearch.ts
> +        where(SEARCH_FIELD, '<=', `${searchText}~`),
Please, move `~` to constant as firebase search symbol

2022-02-09 13:41 UTC, pavel-romanov8 requested changes

2022-02-09 13:41 UTC, pavel-romanov8 commented on vanilla/src/films/renderFilms.ts
> +export let lastDocFilm: QueryDocumentSnapshot<DocumentData> | null = null;
Are you sure that it is a good idea to create global mutable variables that can be changed from anywhere? Please, try to rework your approach to a more safe variant.

2022-02-09 13:41 UTC, pavel-romanov8 commented on vanilla/src/ts/getQuerySearch.ts
> + * @returns
Redundant `returns`

2022-02-09 13:41 UTC, pavel-romanov8 commented on vanilla/src/search/search.ts
> +searchButton?.addEventListener('click', async() => {
Please, add space after `async` keyword

2022-02-09 13:41 UTC, pavel-romanov8 commented on vanilla/src/ts/getQuerySearch.ts
> +import { PaginationDirection } from '../enum/enum';
Please, name file according to enum that placed there, on your case it will be `PaginationDirection`, because it is kinda strange to see imports like `enum/enum/enum`

2022-02-09 13:41 UTC, pavel-romanov8 commented on vanilla/src/search/search.ts
> +export let searchText = '';
Same thing with global mutable variables

2022-02-09 13:41 UTC, pavel-romanov8 commented on vanilla/src/films/renderFilms.ts
> +export let lastDocFilm: QueryDocumentSnapshot<DocumentData> | null = null;
In order to achieve that you can use just standard class with private fields, function for getting a copy of the object from outside, or play with [proxy](https://learn.javascript.ru/proxy).

2022-02-09 13:54 UTC, artem-sotnichenko-saritasa commented on vanilla/src/search/search.ts
> +searchButton?.addEventListener('click', async() => {
It is linter rule.

2022-02-11 01:17 UTC, dbitkovski approved these changes

2022-02-11 12:06 UTC, pavel-romanov8 approved these changes

2022-02-11 12:06 UTC, pavel-romanov8 commented on vanilla/src/services/StoreService.ts
> +  private static _lastDocFilm: QueryDocumentSnapshot<DocumentData> | null = null;
It is a lot better variant than the previous one :+1:

But still, we have some room for possible store mutation because for the last and the first doc we are providing links to store objects that should be private and immutable.

Basically, i can get the store and dig into `firstDocFilm`, change something there and the app might be just broken. Because all clients of the `StoreService` have the same link to the object. For better safety, you can just copy those objects.

And don't forget to declare interface fields as read-only

2022-02-12 04:00 UTC, merged