Feature/js 19 288 init angular/login
saritasa-nest/camp-js-2022-karina-popova pull request #4
Opened 2022-03-01 07:57 UTC by karbik-creator

2022-03-01 10:59 UTC, kristinaSvobodinaSaritasa commented on angular/src/app/app.component.ts
> +  public constructor(
Please, remove empty constructor.

2022-03-01 10:59 UTC, kristinaSvobodinaSaritasa commented on angular/src/app/core/models/Film.ts
> +  readonly created: string;
Why does it have string type? May be it is better to use Date?

2022-03-01 10:59 UTC, kristinaSvobodinaSaritasa commented on angular/src/app/core/models/user.ts
> +  readonly displayName: string | null;
I think it isn't good name for field, it is more suitable for function to display name. Use `name` or `userName`.

2022-03-01 10:59 UTC, kristinaSvobodinaSaritasa commented on angular/src/app/core/services/Firebase.service.ts
> +    this.refCollection = this.firestore.collection('films');
If I remember rightly it is generic, you can write `this.firestore.collection<FilmDTO>('films')` to return correct type

2022-03-01 10:59 UTC, kristinaSvobodinaSaritasa commented on angular/src/app/features/login/login-form/login-form.component.html
> +        <button mat-flat-button color="primary">Sign in</button>
Please, add `type`.

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/app.component.ts
> +  public readonly title = 'sw-films';
Do you need this?

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/core/models/Film.ts
> +  readonly releaseDate: string;
Kristina is right, for date properties we use date format unlike dto entities.

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/core/services/user.service.ts
> +    return signIn$;
You don't need to create a variable, just write return.
```suggestion
    return from(this.auth.signInWithEmailAndPassword(email, password)).pipe(
      map(userCredentil => userCredentil.user ? this.userMapper.fromDto(userCredentil.user) : null)
    );
```

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/core/services/user.service.ts
> +    const signUp$ = from(this.auth.createUserWithEmailAndPassword(email, password))
The same as above.

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/films/film/film.component.html
> +<td>{{ film?.created | date:'d.LL.YYYY'}}</td>
I don't see optional properties in your model. I think you can rewrite it.
```suggestion
<ng-container *ngIf="film !== null">
  <td>{{ film.title }}</td>
  <td>{{ film.director }}</td>
  <td>{{ film.created | date:'d.LL.YYYY'}}</td>
</ng-container>
```

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/films/films-list/films-list.component.html
> +      <div *ngFor="let film of films$ | async">
Don't forget to add `trackBy` function for `ngFor`. [More information](https://frontendwiki.saritasa.rocks/pages/development/angular/practices.html#trackby)

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/login/login-form/login-form.component.ts
> +    ).subscribe({
Don't forget to track your subscriptions and unsubscribe from them before destroying the component.

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/login/register-form/register-form.component.html
> +    <button mat-flat-button color="primary">Sign up</button>
It's better to explicitly specify the type of submit button.

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/login/register-form/register-form.component.ts
> +  public registerForm!: FormGroup;
When you move the form initialization into the constructor, you can get rid of the `!` operator.

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/header/header.component.css
> +.header-wrapper * + *{
Can you make this selector more clear?

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/header/header.component.html
> +        <button mat-raised-button (click)="openDialogSignUp()">Sign Up</button>
Add type for buttons, please)

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/header/header.component.ts
> +  public user$: Observable<User | null>;
Why do you use `@Input()` for `user$`?  I don't see what would be passed to the header component as an input property.

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/header/header.component.ts
> +  public user$: Observable<User | null>;
```suggestion
  public readonly user$ = this.userService.getCurrentUser();
```

2022-03-01 18:39 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/header/header.component.ts
> +  }
Just initialize the variable in the class property declaration, so you don't need it anymore, as I showed above.

2022-03-03 02:53 UTC, timofei-maximov-saritasa requested changes

2022-03-03 02:53 UTC, timofei-maximov-saritasa commented on angular/src/app/core/models/Film.ts
> +  readonly producer: string;
If it is comma separated value, then shouldn't it an array in your model? This way it will be easier for you to iterate.

2022-03-03 02:53 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/mappers/dto/Film/film.dto.ts
> +export interface FilmDTO {
We [prefer to name our dtos](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html) in `PascalCase`. It will be like `FilmDto`

2022-03-03 02:53 UTC, timofei-maximov-saritasa commented on angular/src/app/features/login/login-form/login-form.component.html
> +      <div (click)="openSignUpDialog()" class="button-row">Create New Account</div>
I guess, it should be a `button`

2022-03-03 02:53 UTC, timofei-maximov-saritasa commented on angular/src/app/features/login/login-form/login-form.component.ts
> +  public errorMessage$: Subject<FirebaseError | null> = new ReplaySubject<FirebaseError | null>();
Your component now now about `FirebaseError`. What if we will change firebase to something else? You can map this error into your own, like @DaniilMaslovSaritasa showed you in his lecture.

2022-03-03 02:53 UTC, timofei-maximov-saritasa commented on angular/src/app/features/login/register-form/register-form.component.html
> +</mat-dialog-content>
It seems like your forms are almost identical. Can we reduce code duplication?

2022-03-03 14:02 UTC, chernodub requested changes

2022-03-03 14:02 UTC, chernodub commented on angular/src/app/shared/components/header/header.component.html
> +    <span routerLink="">SW-FILMS</span>
Please make sure it redirects a user to the main page, it is a standard UX practice. As far as I understand it won't work right now, since your routerLink is empty

2022-03-05 14:11 UTC, dbitkovski requested changes

2022-03-05 14:11 UTC, dbitkovski commented on angular/src/app/features/login/register-form/register-form.component.ts
> +  public nameLink = 'Go to Sign In';
I think you can make it `readonly`

2022-03-05 14:11 UTC, dbitkovski commented on angular/src/app/features/login/register-form/register-form.component.ts
> +  private destroy$: Subject<boolean> = new Subject<boolean>();
Stream props should be `readonly` for sure

2022-03-05 14:11 UTC, dbitkovski commented on angular/src/app/shared/pipes/handing-error.pipe.ts
> +    }
I don't really think it should be on UI layer. Let's remove `code` property from the `AppError` class because it seems redundant and map API error in the service

2022-03-10 11:57 UTC, chernodub requested changes

2022-03-10 11:57 UTC, chernodub commented on angular/src/app/features/login/login-form/login-form.component.ts
> +  public onLogin(loginForm: FormGroup): void {
We never allow leaking UI-realated entities to domain layer. Services must operate with domain entities only, this way such classes are un-bound from the UI implementation and it could easily be changed. I recommend you to check out our [architecture guideline ](https://frontendwiki.saritasa.rocks/pages/development/angular/architecture.html)

2022-03-10 11:57 UTC, chernodub commented on angular/src/app/shared/components/header/header.component.html
> +      <span routerLink="/">SW-FILMS</span>
Please always use `<a>` for navigation

2022-03-21 03:53 UTC, chernodub approved these changes

2022-03-21 03:53 UTC, chernodub commented on angular/src/app/core/models/form-value.ts
> +export interface FormValue {
Please resolve the following questions in order to improve the model
1. Which form exactly does it belong ? 
2. Does it really a form value, or a model representing credentials for logging in?

2022-03-22 08:22 UTC, merged