Feature/js 19 288 angular/table
saritasa-nest/camp-js-2022-karina-popova pull request #6
Opened 2022-03-16 09:10 UTC by karbik-creator

2022-03-18 02:06 UTC, pavel-romanov8 requested changes

2022-03-18 02:06 UTC, pavel-romanov8 commented on angular/src/app/core/services/firebase.service.ts
> +  /** Returns a query, including filtering and sorting, pagination.
Please, format your documentation properly

2022-03-18 02:06 UTC, pavel-romanov8 commented on angular/src/app/core/services/mappers/dto/film/film-fields.dto.ts
> +  readonly planets: number[];
Please, declare the array as read-only

2022-03-21 02:35 UTC, chernodub requested changes

2022-03-21 02:35 UTC, chernodub commented on angular/src/app/core/models/table-options.ts
> +import { Sort } from '@angular/material/sort';
Angular Material is a UI-layer and your domain layer should never know anything about UI. Please consider either moving this model out of `core` (and never rely on it in any of `core` models). In order to get more knowledge about our architecture approach, check out our [architecture page in wiki](https://frontendwiki.saritasa.rocks/pages/development/angular/architecture.html#view)

2022-03-21 02:35 UTC, chernodub commented on angular/src/app/core/services/firebase.service.ts
> +          this.firstDoc = documentsDto[0].payload.doc;
Usually, we prefer to move side effects (or state mutations) in `tap` since this is more explicit, therefore, easier to debug. Map is usually a function that accepts a value and transforms it to another value, consider researching [CQS](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation)

2022-03-21 02:35 UTC, chernodub commented on angular/src/app/core/services/firebase.service.ts
> +   * @param options - Parameters for generating a query constraint.
Please be consistent about your JSDoc, either have dashes everywhere or nowhere (we usually prefer avoiding it, since this was initially used to improve readability of JS in IDEs without syntax highlighting, now we have it properly decorated with a color)

2022-03-21 02:35 UTC, chernodub commented on angular/src/app/core/services/firebase.service.ts
> +  public getQueryConstraint(refCollection: CollectionReference<DocumentData>, options: TableOptions, pathField: Path):
Please first make your properties/methods private, and only then, in case you need it outside, make it public. This is one of the main principles of OOP — encapsulation. All the stuff that is not needed outside gotta be isolated.

2022-03-21 02:35 UTC, chernodub commented on angular/src/app/core/services/firebase.service.ts
> +  public getQueryConstraint(refCollection: CollectionReference<DocumentData>, options: TableOptions, pathField: Path):
As I said, `TableOptions` based on UI models. And, since you are using `TableOptions` in your services, you need to make sure you don't depend on UI, otherwise your UI can not be moved away from the domain. This way code becomes non-maintainable and the refactoring becomes more and more complex every time such a dependency happens. As a solution, you could re-create your `TableOptions` to be a self-contained model that would hold all of the information required for pagination.

2022-03-24 10:10 UTC, chernodub requested changes

2022-03-24 10:10 UTC, chernodub commented on angular/src/app/core/models/query-parameters.ts
> +  direction: 'asc' | 'desc' | '';
What does `''` represent? Is there a point in having it? :)

2022-03-24 10:10 UTC, chernodub commented on angular/src/app/core/models/query-parameters.ts
> +  pageIndex: number;
Consider making things `readonly`
https://frontendwiki.saritasa.rocks/development/languages/typescript#promote-immutability

2022-03-24 10:10 UTC, chernodub commented on angular/src/app/core/models/query-parameters.ts
> +  active: string;
Not sure that I get what you mean by `active` and sort field, please be more specific

2022-03-24 10:10 UTC, chernodub commented on angular/src/app/core/models/table-options.ts
> +  readonly searchValue: string;
Is it the same with `query-parameters` ?

2022-03-24 10:10 UTC, chernodub commented on angular/src/app/core/services/mappers/dto/film/film-fields.dto.ts
> +
Seems like the comment above is not resolved

2022-03-28 03:14 UTC, panov-aleksey-saritasa requested changes

2022-03-28 03:14 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-list/films-list.component.ts
> +      .subscribe(value => {
Don't forget to unsubscribe

2022-03-28 03:14 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-list/films-list.component.ts
> +  private readonly destroy$: Subject<void> = new Subject<void>();
You don't need to use type notation here, typescript can infer it by itself :)

2022-03-28 03:14 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-list/films-list.component.ts
> +  @ViewChild('paginator') public paginator!: MatPaginator;
Please, avoid non-null assertion, it's unsafe. Prefer using either `?` or `MatPaginator | null = null` instead

2022-03-28 03:14 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-list/films-list.component.ts
> +  private searchOption$ = new BehaviorSubject('');
Missing readonly

2022-03-28 03:14 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-list/films-list.component.ts
> +    );
Why do you mutating `film$` here?

2022-03-28 03:14 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-list/films-list.component.ts
> +  private tableOptions = combineLatest([this.paginationOptions$, this.sortOptions$, this.searchOption$]);
Please, always add `$` suffix for streams

2022-03-28 03:14 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-list/films-list.component.ts
> +    );
Actually, as I see you don't need that, `next` for pagination options will trigger value emit for `tableOptions` and thus new value will be emitted from `film$` stream

2022-03-28 07:09 UTC, karbik-creator commented on angular/src/app/core/models/query-parameters.ts
> +  sortField: string;
No, I change the value of this parameter if necessary

2022-03-29 03:37 UTC, chernodub commented
@karbik-creator Please consider revising your commit messages, check out our [git guidelines](https://frontendwiki.saritasa.rocks/development/tools/git#commit-messages) and please check an article related

2022-03-29 05:22 UTC, chernodub requested changes

2022-04-04 08:43 UTC, closed without merging