Feature/js 19 300 react/login
saritasa-nest/camp-js-2022-karina-popova pull request #7
Opened 2022-03-22 08:30 UTC by karbik-creator

2022-03-22 08:42 UTC, golovachev-yaroslav approved these changes

2022-03-22 08:42 UTC, golovachev-yaroslav commented on react/src/features/auth/components/Form.tsx
> +  readonly handleSubmit: Function;
It would be better to describe the function
Ex:
`readonly handleSubmit: (data: SomeType) => void;`

2022-03-22 12:11 UTC, ShestakovaElena commented on react/src/features/auth/components/Form.tsx
> +  const [open] = React.useState(true);
It seems strange for me - is Dialog window always open?

2022-03-22 19:00 UTC, pavelzadorin-saritasa requested changes

2022-03-22 19:00 UTC, pavelzadorin-saritasa commented on react/src/store/user/state.ts
> +  user: AuthService.getCurrentUser(),
the Redux main use case is when the initial state is a static object, essentially state default values.
getting some information (even synchronously) is better done with an explicit action, for example: `fetchCurrentUser` which will get the current user from the Firebase and set it in the store.

2022-03-28 06:37 UTC, pavelzadorin-saritasa approved these changes

2022-03-28 06:37 UTC, pavelzadorin-saritasa commented on react/src/store/user/selectors.ts
> +export const selectUser = createSelector((state: RootState) => state.user.user, user => user);
let's keep the consistency, in all other selectors you refer to `state.user` and then you get a specific parameter (like `user.isAuthenticated`), but here you immediately get the parameter. For consistency, it is better to do as in the rest.

2022-03-28 06:48 UTC, kristinaSvobodinaSaritasa approved these changes

2022-03-28 07:15 UTC, merged